### ISSUE TITLE
First session - plans

### ISSUE THREAD

**Issue by partikus** [php-refactor/mail-sender#2]
Hi @php-refactor 

I have pleasure to announce the first meeting's roadmap:

1. Short presentation about business requirements ( speaker: @dominikhajduk ) 
2. Discussing about refactoring plans (writing down all offers)
3. Selecting essential tools e.g. phpunit, phpspec, CI etc. 
4. Preparing app skeleton 
5. .... ?

I'm waiting for your feedback! 

@php-refactor Please put your ideas here!

**Comment by dominikhajduk** [comment]
Plan sounds great. As mentioned on meeting we should try collect list of tutorials how to start with tests mentioned by @partikus.

**Comment by partikus** [comment]
@dominikhajduk if you want then let's learn!
- [PHPSpec](http://www.phpspec.net/en/latest/manual/introduction.html)
- [PHPUnit](https://phpunit.de/documentation.html)
- [Behat](http://behat.readthedocs.org/en/latest/)

I'd like to start develop the app using BDD. But we should know that sometimes phpspec is not enough and we will need to use phpunit instead. 

First of all you should remind [PHP THE RIGHT WAY](http://pl.phptherightway.com/) 

Also I've collected some interesting videos:
- [SymfonyLive London 2013 - Jakub Zalas - Using PhpSpec to build quality into a Symfony app](https://www.youtube.com/watch?v=zSrwu0uQ1VQ)
- [4Developers2015: Jak zacząć pracować z DDD wykorzystując BDD? (K. Gunia)]
(https://www.youtube.com/watch?v=e-NLHHY2YtM)
- [SPUG#4 - Spec BDD w PHP - Kacper Gunia](https://www.youtube.com/watch?v=MvvKrzkDRlI)
- [Introducing Modelling by Example](http://everzet.com/post/99045129766/introducing-modelling-by-example)
- [https://youtu.be/CYEfxW0Ws7Y?t=6h7m45s](https://youtu.be/CYEfxW0Ws7Y?t=6h7m45s) 

As CI tool we're using travis - more info [here](http://docs.travis-ci.com/) 

@php-refactor @dominikhajduk

**Comment by partikus** [comment]
Summarizing first meeting below you can find plans on the next meeting and additional info:

Additional issues to do before next session:
* vagrant (dev env)
* README.md with instructions how to set up project
* LICENSE - MIT - adding file with license
* CONTRIBUTING.md - adding instructions how to contribute to project
* Travis - adding CI tool

Plans for the next session
* quick example how to run project (5min)
* writing testing scenarios in Behat
* showing github/pr flow
* writing functional tests in PHPunit 

@php-refactor @dominikhajduk 
Please fix me if I'm wrong or if I forgot sth.

If you want to prepare some stuff for the next meeting, please to add a comment with the scope of your job

**Comment by partikus** [comment]
@php-refactor @dominikhajduk 
Please see below, we got it! 

<img width="948" alt="zrzut ekranu 2015-09-06 o 21 55 54" src="https://cloud.githubusercontent.com/assets/1732227/9706336/26e8bca2-54e2-11e5-985f-53d000946d15.png">

**Comment by dominikhajduk** [comment]
@php-refactor @partikus great job! Looks like you need update your fork.

**Comment by dominikhajduk** [comment]
@php-refactor can we close this?

**Comment by partikus** [comment]
@dominikhajduk closed
