### ISSUE TITLE
Update composer looking for best way

### ISSUE THREAD

**Issue by dominikhajduk** [php-refactor/mail-sender#25]
@php-refactor I'm looking for best way to update composer for our project. Should there be special option in unusable roles to allow us run `vagrant provision` or we should update composer directly on machine? Best practices here?

**Comment by partikus** [comment]
@dominikhajduk AFAIK composer is installed globally and each time when you `destroy` and `up` machine you composer will be installed in the most recent version, but I suppose you don't want to do that, so you can run ``sudo /usr/local/bin/composer self-update``

**Comment by dominikhajduk** [comment]
@partikus Ok that;s clear for me. Will update on VM. `sudo composer selfupdate` is enough. Thanks
