### ISSUE TITLE
TODO after meeting 3 (@partikus)

### ISSUE THREAD

**Issue by dominikhajduk** [php-refactor/mail-sender#9]
@partikus special for you, feel free to prepare Travis

**Comment by partikus** [comment]
@dominikhajduk @php-refactor 
In order to run tests on travis we have to prepare different configurations. I'm waiting for your ideas and advices for this stuff.

**Comment by partikus** [comment]
@php-refactor ping
any advices?

**Comment by dominikhajduk** [comment]
Perfect work!
